### ISSUE TITLE
Create class BaseClass Model called Test and inherit from it

### ISSUE THREAD

**Issue by driad91** [driad91/BTalaqa#12]
Create Base class model called test, and make MCQTests inherit from it, so that the assignments are done in the assignments app per base test and not per specific type of test, so that in the future any other types of tests could be assigned in the same table as well. (Not sure if it's possible!)

**Comment by protvino** [comment]
I think we should move the m2m relationship between user and test to MCQApp and (maybe) remove assignments app...
imho it won't be possible to join all possible future apps on the database level, without introducing some crazy database structure. 
It will be much easier to have a view somewhere that will just collect all mappings between users and tests from various apps (MCQ App, Essay app, etc...) It will allow to flexibly add apps without painful database migrations.

**Comment by protvino** [comment]
Please, see WIP pull request
