### ISSUE TITLE
Creating multiple correct answers to the same question.

### ISSUE THREAD

**Issue by driad91** [driad91/BTalaqa#27]
If multiple answers are marked correct while creating one question, only the first one is saved in the database as correct.

The idea for now is that the student could choose only one answer however if there are many correct answers he doesn't have to choose all but they would all be accepted as correct.

That was mainly the initial idea of exclusive answer in the question table, that the student have only to tick one answer and not all possible correct answers.

**Comment by protvino** [comment]
Solved, see pull request
