### ISSUE TITLE
Bug in test submission

### ISSUE THREAD

**Issue by vvkorz** [driad91/BTalaqa#48]
There is a serious bug in test submission.
It is in the ajax submission of students answers and rendering of the test page. It only can handle one answer per question. This is partially due to the fact how test page is rendered, where only one answer in multiple choice is possible, and also partially due to how the ajax is coded, where a dict with questions as keys and answers as values is generated. 

see
 - questionAnswersDict in ChekTest.js
 - student_answers in test_correction() method in test_helper.py

While correcting this issue one has to take into account that the code in render_test() view relies on this assumption and also should be corrected.

**Comment by driad91** [comment]
Not really a bug, as discussed!
